### ISSUE TITLE
The bundle is breaking on newer version of eZ Publish 5.4.9.1

### ISSUE THREAD

**Issue by ernestob** [netgen/NetgenEnhancedSelectionBundle#18]
I am having an issue with the Netgen enhanced selection bundle.

I am doing an update to **eZ Publish 5.4.9.1** everything goes well, but in the end I am getting this message:
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
 The service "ezpublish.search.solr.criterion_visitor.enhanced_selection" has a dependency on a non-existent service "ezpublish.search.common.field_value_mapper.aggregate".
```
When I do a cache clear I am getting the same message.

I have enabled the legacy search as noted in this link: https://doc.ez.no/display/EZP/Legacy+Search+Engine+Bundle

ezpublish.yml
```
ezpublish:
    repositories:
        main_repository:
            storage:
                engine: legacy
                connection: default
            search:
                engine: legacy
                connection: default
```
Still not working.

Disabling the bundle from the EzPublishKernel, let me clear the cache without any issue.
